name: lifepath
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  location: ^6.0.2
  google_maps_flutter: ^2.6.1
  mqtt_client: ^10.3.0

flutter:
  uses-material-design: true
